"""Shared shapes the per-agent parsers produce."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

# Both CLIs wrap machine-injected context around what the human actually typed.
# Titles and previews are derived from the human part only.
_CODEX_REQUEST = re.compile(r"##\s*My request for Codex:\s*(.*)", re.S)
_COMMAND_NAME = re.compile(r"<command-name>\s*(.*?)\s*</command-name>", re.S)
_WRAPPERS = re.compile(
    r"</?(?:command-name|command-message|command-args|local-command-caveat"
    r"|local-command-stdout|system-reminder|user-prompt-submit-hook)>",
    re.I,
)
# Prefixes that mark a whole message as injected context rather than a prompt.
_INJECTED_PREFIXES = (
    "# AGENTS.md",
    "# Context from my IDE setup",
    "<INSTRUCTIONS>",
    "Caveat: The messages below were generated by the user",
)


def clean_prompt(text: str | None) -> str:
    """Reduce a raw user record to the words the human typed.

    Returns "" when the record carries no human input at all (injected
    instructions, IDE context dumps), so callers can fall through to the next
    candidate rather than titling a session with boilerplate.
    """
    if not text:
        return ""
    s: str = text
    # Codex prepends IDE context; the real ask follows this marker.
    m = _CODEX_REQUEST.search(s)
    if m:
        s = m.group(1)
    # A slash command: the command itself is the prompt.
    m = _COMMAND_NAME.search(s)
    if m and m.group(1).strip():
        return m.group(1).strip()
    s = _WRAPPERS.sub(" ", s).strip()
    for prefix in _INJECTED_PREFIXES:
        if s.startswith(prefix):
            return ""
    return re.sub(r"[ \t]+", " ", s).strip()

# Per-message text caps. Tool results are the bulk of a transcript's bytes
# (file dumps, command output), so they get a tighter cap than prose.
TEXT_CAP = 16_000
TOOL_RESULT_CAP = 4_000


def clip(text: str | None, cap: int = TEXT_CAP) -> tuple[str, bool]:
    """Return (possibly truncated text, was_truncated)."""
    if not text:
        return "", False
    if len(text) <= cap:
        return text, False
    return text[:cap], True


@dataclass
class Message:
    seq: int
    ts: str | None
    role: str  # user | assistant | tool | system
    kind: str  # text | thinking | tool_use | tool_result | image
    text: str
    tool_name: str | None = None
    model: str | None = None
    truncated: bool = False
    sidechain: bool = False  # produced by a subagent, not the main loop
    label: str | None = None  # which subagent/workflow, when sidechain


@dataclass
class Session:
    agent: str
    session_id: str
    path: str
    title: str | None = None
    cwd: str | None = None
    project: str | None = None
    git_branch: str | None = None
    models: list[str] = field(default_factory=list)
    version: str | None = None
    started_at: str | None = None
    ended_at: str | None = None
    first_prompt: str | None = None
    last_prompt: str | None = None

    n_user: int = 0
    n_assistant: int = 0
    n_tool_calls: int = 0
    n_subagents: int = 0

    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_write_tokens: int = 0
    cost_usd: float | None = None
    unpriced: bool = False

    messages: list[Message] = field(default_factory=list)

    @property
    def key(self) -> str:
        return f"{self.agent}:{self.session_id}"

    @property
    def total_tokens(self) -> int:
        return (
            self.input_tokens
            + self.output_tokens
            + self.cache_read_tokens
            + self.cache_write_tokens
        )
